import { OrderService } from '../order.service';
import { CreateOrderDto } from '../dto/create-order.dto';
import { OrderStatus } from '@prisma/client';
import { SubmitOrderReviewDto } from '../dto/submit-review.dto';
import { ReviewService } from '../review.service';
export declare class OrderController {
    private readonly orderService;
    private readonly reviewService;
    constructor(orderService: OrderService, reviewService: ReviewService);
    preview(req: any, dto: CreateOrderDto): Promise<{
        breakdown: any[];
        summary: {
            subtotal: number;
            shippingFee: number;
            giftFee: number;
            discounts: {
                shopVoucher: number;
                systemVoucher: number;
                freeship: number;
                coin: number;
            };
            total: number;
        };
        appliedVouchers: any[];
    }>;
    create(req: any, dto: CreateOrderDto): Promise<{
        success: boolean;
        message: string;
        orders: {
            id: string;
            userId: string;
            status: import("@prisma/client").$Enums.OrderStatus;
            totalAmount: import("@prisma/client/runtime/library").Decimal;
            shippingFee: import("@prisma/client/runtime/library").Decimal;
            voucherId: string | null;
            appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
            shippingOrderCode: string | null;
            shippingProvider: string | null;
            isReviewed: boolean;
            shopId: string | null;
            districtId: number | null;
            wardCode: string | null;
            provinceId: number | null;
            recipientName: string | null;
            recipientPhone: string | null;
            recipientAddress: string | null;
            message: string | null;
            isGift: boolean;
            paymentMethod: string;
            paymentStatus: string;
            coinUsed: number;
            paymentGroupId: string | null;
            clientIp: string | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        paymentUrl: string | null;
    }>;
    submitReview(user: any, dto: SubmitOrderReviewDto): Promise<{
        success: boolean;
        message: string;
        order: {
            id: string;
            userId: string;
            status: import("@prisma/client").$Enums.OrderStatus;
            totalAmount: import("@prisma/client/runtime/library").Decimal;
            shippingFee: import("@prisma/client/runtime/library").Decimal;
            voucherId: string | null;
            appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
            shippingOrderCode: string | null;
            shippingProvider: string | null;
            isReviewed: boolean;
            shopId: string | null;
            districtId: number | null;
            wardCode: string | null;
            provinceId: number | null;
            recipientName: string | null;
            recipientPhone: string | null;
            recipientAddress: string | null;
            message: string | null;
            isGift: boolean;
            paymentMethod: string;
            paymentStatus: string;
            coinUsed: number;
            paymentGroupId: string | null;
            clientIp: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    findAll(req: any, status?: string): Promise<({
        shop: {
            id: string;
            name: string;
            avatar: string | null;
        } | null;
        items: ({
            product: {
                id: string;
                name: string;
                shopId: string | null;
                slug: string;
                images: import("@prisma/client").Prisma.JsonValue;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    getSellerOrders(req: any, status?: string): Promise<({
        user: {
            name: string | null;
            phone: string | null;
        };
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                description: string | null;
                shortDesc: import("@prisma/client").Prisma.JsonValue | null;
                price: import("@prisma/client/runtime/library").Decimal;
                originalPrice: import("@prisma/client/runtime/library").Decimal | null;
                stock: number;
                reviewCount: number;
                systemTags: import("@prisma/client").Prisma.JsonValue;
                images: import("@prisma/client").Prisma.JsonValue;
                status: import("@prisma/client").$Enums.ProductStatus;
                rejectReason: string | null;
                attributes: import("@prisma/client").Prisma.JsonValue | null;
                tags: string | null;
                brandId: number | null;
                shopCategoryId: string | null;
                salesCount: number;
                rating: number;
                shopId: string | null;
                weight: number;
                sellerId: string | null;
                categoryId: string | null;
                discountType: import("@prisma/client").$Enums.DiscountType | null;
                discountValue: import("@prisma/client/runtime/library").Decimal | null;
                discountStartDate: Date | null;
                discountEndDate: Date | null;
                isDiscountActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    confirmReceived(req: any, id: string): Promise<{
        success: boolean;
        orderId: string;
        earnedPoints: number;
        newBalance: number;
    }>;
    findOne(req: any, id: string): Promise<{
        shop: {
            id: string;
            name: string;
        } | null;
        voucher: {
            id: string;
            code: string;
            name: string;
            description: string | null;
            type: import("@prisma/client").$Enums.VoucherType;
            scope: import("@prisma/client").$Enums.VoucherScope;
            amount: import("@prisma/client/runtime/library").Decimal;
            maxDiscount: import("@prisma/client/runtime/library").Decimal | null;
            minOrderValue: import("@prisma/client/runtime/library").Decimal;
            usageLimit: number;
            usageCount: number;
            userUsageLimit: number;
            startDate: Date;
            endDate: Date;
            isActive: boolean;
            shopId: string | null;
            sellerId: string | null;
            createdAt: Date;
            updatedAt: Date;
            version: number;
        } | null;
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                images: import("@prisma/client").Prisma.JsonValue;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateStatus(id: string, status: OrderStatus, req: any): Promise<{
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    getSellerOrderDetail(id: string, req: any): Promise<{
        user: {
            email: string | null;
            name: string | null;
            phone: string | null;
        };
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                description: string | null;
                shortDesc: import("@prisma/client").Prisma.JsonValue | null;
                price: import("@prisma/client/runtime/library").Decimal;
                originalPrice: import("@prisma/client/runtime/library").Decimal | null;
                stock: number;
                reviewCount: number;
                systemTags: import("@prisma/client").Prisma.JsonValue;
                images: import("@prisma/client").Prisma.JsonValue;
                status: import("@prisma/client").$Enums.ProductStatus;
                rejectReason: string | null;
                attributes: import("@prisma/client").Prisma.JsonValue | null;
                tags: string | null;
                brandId: number | null;
                shopCategoryId: string | null;
                salesCount: number;
                rating: number;
                shopId: string | null;
                weight: number;
                sellerId: string | null;
                categoryId: string | null;
                discountType: import("@prisma/client").$Enums.DiscountType | null;
                discountValue: import("@prisma/client/runtime/library").Decimal | null;
                discountStartDate: Date | null;
                discountEndDate: Date | null;
                isDiscountActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: import("@prisma/client/runtime/library").Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    cancelOrder(req: any, id: string): Promise<{
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        shippingFee: import("@prisma/client/runtime/library").Decimal;
        voucherId: string | null;
        appliedVoucherIds: import("@prisma/client").Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
}
