import { PrismaService } from '../../database/prisma/prisma.service';
import { CartService } from '../../modules/cart/cart.service';
import { PromotionService } from '../../modules/promotion/promotion.service';
import { TrackingService } from '../../modules/tracking/tracking.service';
import { CreateOrderDto } from './dto/create-order.dto';
import { PointService } from '../../modules/point/point.service';
import { OrderStatus, Prisma } from '@prisma/client';
import { GhnService } from '../../modules/ghn/ghn.service';
import { PaymentService } from '../payment/payment.service';
import { CharityService } from '../charity/charity.service';
import { SystemSettingService } from '../../common/services/system-setting.service';
import { NotificationService } from '../notification/notification.service';
export declare class OrderService {
    private prisma;
    private cartService;
    private promotionService;
    private trackingService;
    private pointService;
    private ghnService;
    private paymentService;
    private charityService;
    private systemSetting;
    private notificationService;
    private readonly logger;
    constructor(prisma: PrismaService, cartService: CartService, promotionService: PromotionService, trackingService: TrackingService, pointService: PointService, ghnService: GhnService, paymentService: PaymentService, charityService: CharityService, systemSetting: SystemSettingService, notificationService: NotificationService);
    private resolveItemsAndGroup;
    previewOrder(userId: string, dto: CreateOrderDto): Promise<{
        breakdown: any[];
        summary: {
            subtotal: number;
            shippingFee: number;
            giftFee: number;
            discounts: {
                shopVoucher: number;
                systemVoucher: number;
                freeship: number;
                coin: number;
            };
            total: number;
        };
        appliedVouchers: any[];
    }>;
    createOrder(userId: string, dto: CreateOrderDto, clientIp?: string | null): Promise<{
        orders: {
            id: string;
            userId: string;
            status: import("@prisma/client").$Enums.OrderStatus;
            totalAmount: Prisma.Decimal;
            shippingFee: Prisma.Decimal;
            voucherId: string | null;
            appliedVoucherIds: Prisma.JsonValue | null;
            shippingOrderCode: string | null;
            shippingProvider: string | null;
            isReviewed: boolean;
            shopId: string | null;
            districtId: number | null;
            wardCode: string | null;
            provinceId: number | null;
            recipientName: string | null;
            recipientPhone: string | null;
            recipientAddress: string | null;
            message: string | null;
            isGift: boolean;
            paymentMethod: string;
            paymentStatus: string;
            coinUsed: number;
            paymentGroupId: string | null;
            clientIp: string | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        paymentUrl: string | null;
        totalAmount: number;
    }>;
    findAll(params: {
        page?: number;
        limit?: number;
        status?: string;
        search?: string;
    }): Promise<{
        data: ({
            user: {
                id: string;
                email: string | null;
                name: string | null;
                avatar: string | null;
            };
            items: {
                id: string;
                orderId: string;
                productId: string | null;
                variantId: string | null;
                flashSaleProductId: string | null;
                quantity: number;
                price: Prisma.Decimal;
            }[];
        } & {
            id: string;
            userId: string;
            status: import("@prisma/client").$Enums.OrderStatus;
            totalAmount: Prisma.Decimal;
            shippingFee: Prisma.Decimal;
            voucherId: string | null;
            appliedVoucherIds: Prisma.JsonValue | null;
            shippingOrderCode: string | null;
            shippingProvider: string | null;
            isReviewed: boolean;
            shopId: string | null;
            districtId: number | null;
            wardCode: string | null;
            provinceId: number | null;
            recipientName: string | null;
            recipientPhone: string | null;
            recipientAddress: string | null;
            message: string | null;
            isGift: boolean;
            paymentMethod: string;
            paymentStatus: string;
            coinUsed: number;
            paymentGroupId: string | null;
            clientIp: string | null;
            createdAt: Date;
            updatedAt: Date;
        })[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getUserOrders(userId: string, status?: string): Promise<({
        shop: {
            id: string;
            name: string;
            avatar: string | null;
        } | null;
        items: ({
            product: {
                id: string;
                name: string;
                shopId: string | null;
                slug: string;
                images: Prisma.JsonValue;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: Prisma.Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    getSellerOrders(userId: string, status?: string): Promise<({
        user: {
            name: string | null;
            phone: string | null;
        };
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                description: string | null;
                shortDesc: Prisma.JsonValue | null;
                price: Prisma.Decimal;
                originalPrice: Prisma.Decimal | null;
                stock: number;
                reviewCount: number;
                systemTags: Prisma.JsonValue;
                images: Prisma.JsonValue;
                status: import("@prisma/client").$Enums.ProductStatus;
                rejectReason: string | null;
                attributes: Prisma.JsonValue | null;
                tags: string | null;
                brandId: number | null;
                shopCategoryId: string | null;
                salesCount: number;
                rating: number;
                shopId: string | null;
                weight: number;
                sellerId: string | null;
                categoryId: string | null;
                discountType: import("@prisma/client").$Enums.DiscountType | null;
                discountValue: Prisma.Decimal | null;
                discountStartDate: Date | null;
                discountEndDate: Date | null;
                isDiscountActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: Prisma.Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    cancelOrder(userId: string, orderId: string): Promise<{
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    confirmOrderReceived(userId: string, orderId: string): Promise<{
        success: boolean;
        orderId: string;
        earnedPoints: number;
        newBalance: number;
    }>;
    private processReferralReward;
    private creditSellerOnDelivered;
    updateOrderStatus(orderId: string, sellerId: string, status: OrderStatus): Promise<{
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    } | null>;
    getSellerOrderDetail(orderId: string, sellerId: string): Promise<{
        user: {
            email: string | null;
            name: string | null;
            phone: string | null;
        };
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                description: string | null;
                shortDesc: Prisma.JsonValue | null;
                price: Prisma.Decimal;
                originalPrice: Prisma.Decimal | null;
                stock: number;
                reviewCount: number;
                systemTags: Prisma.JsonValue;
                images: Prisma.JsonValue;
                status: import("@prisma/client").$Enums.ProductStatus;
                rejectReason: string | null;
                attributes: Prisma.JsonValue | null;
                tags: string | null;
                brandId: number | null;
                shopCategoryId: string | null;
                salesCount: number;
                rating: number;
                shopId: string | null;
                weight: number;
                sellerId: string | null;
                categoryId: string | null;
                discountType: import("@prisma/client").$Enums.DiscountType | null;
                discountValue: Prisma.Decimal | null;
                discountStartDate: Date | null;
                discountEndDate: Date | null;
                isDiscountActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: Prisma.Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findOne(id: string, userId: string): Promise<{
        shop: {
            id: string;
            name: string;
        } | null;
        voucher: {
            id: string;
            code: string;
            name: string;
            description: string | null;
            type: import("@prisma/client").$Enums.VoucherType;
            scope: import("@prisma/client").$Enums.VoucherScope;
            amount: Prisma.Decimal;
            maxDiscount: Prisma.Decimal | null;
            minOrderValue: Prisma.Decimal;
            usageLimit: number;
            usageCount: number;
            userUsageLimit: number;
            startDate: Date;
            endDate: Date;
            isActive: boolean;
            shopId: string | null;
            sellerId: string | null;
            createdAt: Date;
            updatedAt: Date;
            version: number;
        } | null;
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                images: Prisma.JsonValue;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: Prisma.Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findOneAsAdmin(id: string): Promise<{
        user: {
            id: string;
            email: string | null;
            name: string | null;
            phone: string | null;
            avatar: string | null;
        };
        shop: {
            id: string;
            name: string;
            slug: string;
        } | null;
        voucher: {
            id: string;
            code: string;
            name: string;
            description: string | null;
            type: import("@prisma/client").$Enums.VoucherType;
            scope: import("@prisma/client").$Enums.VoucherScope;
            amount: Prisma.Decimal;
            maxDiscount: Prisma.Decimal | null;
            minOrderValue: Prisma.Decimal;
            usageLimit: number;
            usageCount: number;
            userUsageLimit: number;
            startDate: Date;
            endDate: Date;
            isActive: boolean;
            shopId: string | null;
            sellerId: string | null;
            createdAt: Date;
            updatedAt: Date;
            version: number;
        } | null;
        items: ({
            product: {
                id: string;
                name: string;
                slug: string;
                price: Prisma.Decimal;
                images: Prisma.JsonValue;
            } | null;
        } & {
            id: string;
            orderId: string;
            productId: string | null;
            variantId: string | null;
            flashSaleProductId: string | null;
            quantity: number;
            price: Prisma.Decimal;
        })[];
    } & {
        id: string;
        userId: string;
        status: import("@prisma/client").$Enums.OrderStatus;
        totalAmount: Prisma.Decimal;
        shippingFee: Prisma.Decimal;
        voucherId: string | null;
        appliedVoucherIds: Prisma.JsonValue | null;
        shippingOrderCode: string | null;
        shippingProvider: string | null;
        isReviewed: boolean;
        shopId: string | null;
        districtId: number | null;
        wardCode: string | null;
        provinceId: number | null;
        recipientName: string | null;
        recipientPhone: string | null;
        recipientAddress: string | null;
        message: string | null;
        isGift: boolean;
        paymentMethod: string;
        paymentStatus: string;
        coinUsed: number;
        paymentGroupId: string | null;
        clientIp: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
}
