import { PrismaService } from '../../database/prisma/prisma.service';
import { CreateShopDto } from './dto/create-shop.dto';
import { Prisma } from '@prisma/client';
import { UpdateShopProfileDto } from '../auth/dto/update-shop.dto';
export declare class ShopService {
    private prisma;
    constructor(prisma: PrismaService);
    private resolveShopId;
    createShop(userId: string, data: CreateShopDto): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        avatar: string | null;
        coverImage: string | null;
        pickupAddress: string | null;
        provinceId: number | null;
        districtId: number | null;
        wardCode: string | null;
        lat: number | null;
        lng: number | null;
        categoryId: string | null;
        status: import("@prisma/client").$Enums.ShopStatus;
        banReason: string | null;
        reviewCount: number;
        decoration: Prisma.JsonValue | null;
        pendingDetails: Prisma.JsonValue | null;
        rating: number;
        totalSales: number;
        ownerId: string;
        address: string | null;
        licenseImage: string | null;
        taxCode: string | null;
        businessLicenseFront: string | null;
        businessLicenseBack: string | null;
        salesLicense: string | null;
        trademarkCert: string | null;
        distributorCert: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getShopCustomCategories(shopIdOrSlug: string): Promise<({
        _count: {
            products: number;
        };
    } & {
        id: string;
        name: string;
        isActive: boolean;
        shopId: string;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    getShopCategories(shopId: string): Promise<{
        id: string;
        name: string;
        slug: string;
        image: string | null;
    }[]>;
    getShopProducts(shopIdOrSlug: string, params: any): Promise<{
        data: {
            id: string;
            name: string;
            createdAt: Date;
            slug: string;
            rating: number;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            stock: number;
            images: Prisma.JsonValue;
            salesCount: number;
        }[];
        meta: {
            total: number;
            page: number;
            limit: number;
            last_page: number;
        };
    }>;
    getPublicProfile(idOrSlug: string): Promise<{
        totalProducts: number;
        id: string;
        name: string;
        avatar: string | null;
        createdAt: Date;
        description: string | null;
        coverImage: string | null;
        _count: {
            products: number;
        };
        status: import("@prisma/client").$Enums.ShopStatus;
        decoration: Prisma.JsonValue;
        rating: number;
        totalSales: number;
    }>;
    getShops(query: any): Promise<{
        data: {
            id: string;
            name: string;
            avatar: string | null;
            slug: string;
        }[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getShopVouchers(shopIdOrSlug: string): Promise<{
        id: string;
        description: string | null;
        type: import("@prisma/client").$Enums.VoucherType;
        code: string;
        amount: Prisma.Decimal;
        endDate: Date;
        minOrderValue: Prisma.Decimal;
    }[]>;
    getShopByOwnerId(userId: string): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        avatar: string | null;
        coverImage: string | null;
        pickupAddress: string | null;
        provinceId: number | null;
        districtId: number | null;
        wardCode: string | null;
        lat: number | null;
        lng: number | null;
        categoryId: string | null;
        status: import("@prisma/client").$Enums.ShopStatus;
        banReason: string | null;
        reviewCount: number;
        decoration: Prisma.JsonValue | null;
        pendingDetails: Prisma.JsonValue | null;
        rating: number;
        totalSales: number;
        ownerId: string;
        address: string | null;
        licenseImage: string | null;
        taxCode: string | null;
        businessLicenseFront: string | null;
        businessLicenseBack: string | null;
        salesLicense: string | null;
        trademarkCert: string | null;
        distributorCert: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateShopProfile(userId: string, data: UpdateShopProfileDto): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        avatar: string | null;
        coverImage: string | null;
        pickupAddress: string | null;
        provinceId: number | null;
        districtId: number | null;
        wardCode: string | null;
        lat: number | null;
        lng: number | null;
        categoryId: string | null;
        status: import("@prisma/client").$Enums.ShopStatus;
        banReason: string | null;
        reviewCount: number;
        decoration: Prisma.JsonValue | null;
        pendingDetails: Prisma.JsonValue | null;
        rating: number;
        totalSales: number;
        ownerId: string;
        address: string | null;
        licenseImage: string | null;
        taxCode: string | null;
        businessLicenseFront: string | null;
        businessLicenseBack: string | null;
        salesLicense: string | null;
        trademarkCert: string | null;
        distributorCert: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateDecoration(userId: string, decoration: any): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        avatar: string | null;
        coverImage: string | null;
        pickupAddress: string | null;
        provinceId: number | null;
        districtId: number | null;
        wardCode: string | null;
        lat: number | null;
        lng: number | null;
        categoryId: string | null;
        status: import("@prisma/client").$Enums.ShopStatus;
        banReason: string | null;
        reviewCount: number;
        decoration: Prisma.JsonValue | null;
        pendingDetails: Prisma.JsonValue | null;
        rating: number;
        totalSales: number;
        ownerId: string;
        address: string | null;
        licenseImage: string | null;
        taxCode: string | null;
        businessLicenseFront: string | null;
        businessLicenseBack: string | null;
        salesLicense: string | null;
        trademarkCert: string | null;
        distributorCert: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getShopBySlug(slug: string): Promise<{
        products: {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            shortDesc: Prisma.JsonValue | null;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            stock: number;
            reviewCount: number;
            systemTags: Prisma.JsonValue;
            images: Prisma.JsonValue;
            status: import("@prisma/client").$Enums.ProductStatus;
            rejectReason: string | null;
            attributes: Prisma.JsonValue | null;
            tags: string | null;
            brandId: number | null;
            shopCategoryId: string | null;
            salesCount: number;
            rating: number;
            shopId: string | null;
            weight: number;
            sellerId: string | null;
            categoryId: string | null;
            discountType: import("@prisma/client").$Enums.DiscountType | null;
            discountValue: Prisma.Decimal | null;
            discountStartDate: Date | null;
            discountEndDate: Date | null;
            isDiscountActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        avatar: string | null;
        coverImage: string | null;
        pickupAddress: string | null;
        provinceId: number | null;
        districtId: number | null;
        wardCode: string | null;
        lat: number | null;
        lng: number | null;
        categoryId: string | null;
        status: import("@prisma/client").$Enums.ShopStatus;
        banReason: string | null;
        reviewCount: number;
        decoration: Prisma.JsonValue | null;
        pendingDetails: Prisma.JsonValue | null;
        rating: number;
        totalSales: number;
        ownerId: string;
        address: string | null;
        licenseImage: string | null;
        taxCode: string | null;
        businessLicenseFront: string | null;
        businessLicenseBack: string | null;
        salesLicense: string | null;
        trademarkCert: string | null;
        distributorCert: string | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
}
