import { JwtService } from '@nestjs/jwt';
import { PrismaService } from '../../database/prisma/prisma.service';
import { MailerService } from '@nestjs-modules/mailer';
import { RedisService } from '../../database/redis/redis.service';
import { UpdateShopProfileDto } from './dto/update-shop.dto';
import { RegisterDto, LoginDto, VerifyOtpDto } from './dto/auth.dto';
import { RegisterSellerDto } from './dto/register-seller.dto';
import { ChangePasswordDto, ForgotPasswordDto, ResetPasswordDto } from './dto/password.dto';
import { UpdateProfileDto } from './dto/update-profile.dto';
export declare class AuthService {
    private prisma;
    private redisService;
    private jwtService;
    private mailerService;
    private static readonly OTP_TTL_SECONDS;
    private static readonly OTP_KEY_PREFIX;
    private static readonly PWD_RESET_TTL_SECONDS;
    private static readonly PWD_RESET_KEY_PREFIX;
    constructor(prisma: PrismaService, redisService: RedisService, jwtService: JwtService, mailerService: MailerService);
    private otpKey;
    private pwdResetKey;
    register(dto: RegisterDto): Promise<{
        devOtp?: string | null | undefined;
        message: string;
    }>;
    registerSeller(dto: RegisterSellerDto): Promise<{
        message: string;
    }>;
    login(dto: LoginDto, allowedRoles?: string[]): Promise<{
        access_token: string;
        user: any;
    }>;
    verifyOtp(dto: VerifyOtpDto): Promise<{
        access_token: string;
        user: any;
    }>;
    private isMailConfigured;
    sendOtp(email?: string): Promise<{
        otp: string | null;
        mailConfigured: boolean;
    }>;
    private generateTokens;
    updateShopProfile(userId: string, data: UpdateShopProfileDto): Promise<{
        message: string;
        shop: {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            avatar: string | null;
            coverImage: string | null;
            pickupAddress: string | null;
            provinceId: number | null;
            districtId: number | null;
            wardCode: string | null;
            lat: number | null;
            lng: number | null;
            categoryId: string | null;
            status: import("@prisma/client").$Enums.ShopStatus;
            banReason: string | null;
            reviewCount: number;
            decoration: import("@prisma/client").Prisma.JsonValue | null;
            pendingDetails: import("@prisma/client").Prisma.JsonValue | null;
            rating: number;
            totalSales: number;
            ownerId: string;
            address: string | null;
            licenseImage: string | null;
            taxCode: string | null;
            businessLicenseFront: string | null;
            businessLicenseBack: string | null;
            salesLicense: string | null;
            trademarkCert: string | null;
            distributorCert: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    updateProfile(userId: string, dto: UpdateProfileDto): Promise<{
        id: string;
        email: string | null;
        username: string | null;
        isVerified: boolean;
        tokenVersion: number;
        referredById: string | null;
        referralRewardPaid: boolean;
        name: string | null;
        phone: string | null;
        avatar: string | null;
        gender: string | null;
        dob: Date | null;
        role: import("@prisma/client").$Enums.Role;
        isBanned: boolean;
        banReason: string | null;
        walletBalance: import("@prisma/client/runtime/library").Decimal;
        shopId: string | null;
        points: number;
        lastCheckIn: Date | null;
        checkInStreak: number;
        createdAt: Date;
        updatedAt: Date;
        shopName: string | null;
        pickupAddress: string | null;
        description: string | null;
        coverImage: string | null;
    }>;
    getUserProfile(userId: string): Promise<{
        point: any;
        shop: {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            avatar: string | null;
            coverImage: string | null;
            pickupAddress: string | null;
            provinceId: number | null;
            districtId: number | null;
            wardCode: string | null;
            lat: number | null;
            lng: number | null;
            categoryId: string | null;
            status: import("@prisma/client").$Enums.ShopStatus;
            banReason: string | null;
            reviewCount: number;
            decoration: import("@prisma/client").Prisma.JsonValue | null;
            pendingDetails: import("@prisma/client").Prisma.JsonValue | null;
            rating: number;
            totalSales: number;
            ownerId: string;
            address: string | null;
            licenseImage: string | null;
            taxCode: string | null;
            businessLicenseFront: string | null;
            businessLicenseBack: string | null;
            salesLicense: string | null;
            trademarkCert: string | null;
            distributorCert: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        id: string;
        email: string | null;
        username: string | null;
        isVerified: boolean;
        tokenVersion: number;
        referredById: string | null;
        referralRewardPaid: boolean;
        name: string | null;
        phone: string | null;
        avatar: string | null;
        gender: string | null;
        dob: Date | null;
        role: import("@prisma/client").$Enums.Role;
        isBanned: boolean;
        banReason: string | null;
        walletBalance: import("@prisma/client/runtime/library").Decimal;
        shopId: string | null;
        points: number;
        lastCheckIn: Date | null;
        checkInStreak: number;
        createdAt: Date;
        updatedAt: Date;
        shopName: string | null;
        pickupAddress: string | null;
        description: string | null;
        coverImage: string | null;
    }>;
    changePassword(userId: string, dto: ChangePasswordDto): Promise<{
        message: string;
        access_token: string;
    }>;
    forgotPassword(dto: ForgotPasswordDto): Promise<{
        message: string;
    }>;
    resetPassword(dto: ResetPasswordDto): Promise<{
        message: string;
    }>;
    handleOAuthLogin(profile: {
        provider: 'google' | 'facebook';
        providerId: string;
        email: string;
        name: string;
        avatar?: string;
    }): Promise<{
        access_token: string;
        user: any;
    }>;
}
