import { PrismaService } from '../../../database/prisma/prisma.service';
import { CreateProductDto } from '../dto/create-product.dto';
import { ProductCacheService } from './product-cache.service';
import { Prisma } from '@prisma/client';
import { UpdateProductDiscountDto, UpdateProductDto } from '../dto/update-product.dto';
import { ProductReadService } from './product-read.service';
import { ImageSearchService } from '../../image-search/image-search.service';
export declare class ProductWriteService {
    private readonly prisma;
    private readonly productCache;
    private readonly productReadService;
    private readonly imageSearch;
    private readonly logger;
    constructor(prisma: PrismaService, productCache: ProductCacheService, productReadService: ProductReadService, imageSearch: ImageSearchService);
    private safeEnqueueIndex;
    create(userId: string, dto: CreateProductDto): Promise<({
        options: ({
            values: {
                id: string;
                optionId: string;
                value: string;
                image: string | null;
                position: number;
            }[];
        } & {
            id: string;
            productId: string;
            name: string;
            position: number;
        })[];
        variants: {
            id: string;
            productId: string;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            discountValue: Prisma.Decimal | null;
            stock: number;
            sku: string | null;
            image: string | null;
            tierIndex: string;
        }[];
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }) | null>;
    updateProductTags(id: string, systemTags: string[]): Promise<{
        shop: {
            id: string;
            name: string;
            avatar: string | null;
        } | null;
        category: {
            id: string;
            name: string;
            slug: string;
            image: string | null;
            parentId: string | null;
            order: number;
            filterKeys: Prisma.JsonValue | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    approveProduct(productId: string, status: 'ACTIVE' | 'REJECTED', reason?: string): Promise<{
        shop: {
            id: string;
            name: string;
            avatar: string | null;
        } | null;
        variants: {
            id: string;
            productId: string;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            discountValue: Prisma.Decimal | null;
            stock: number;
            sku: string | null;
            image: string | null;
            tierIndex: string;
        }[];
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    bulkApproveProducts(ids: string[], status: 'ACTIVE' | 'REJECTED', reason?: string): Promise<{
        count: number;
    }>;
    delete(id: string): Promise<{
        count: number;
        message?: undefined;
    } | {
        count: number;
        message: string;
    }>;
    bulkDelete(ids: string[]): Promise<{
        count: number;
        message?: undefined;
    } | {
        count: number;
        message: string;
    }>;
    private clearCacheBackground;
    deleteAll(): Promise<{
        count: number;
        message: string;
    }>;
    private safeDelete;
    update(id: string, userId: string, dto: UpdateProductDto): Promise<{
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findOneForEdit(userId: string, productId: string): Promise<{
        price: number;
        originalPrice: number | null;
        brand: any;
        origin: any;
        videos: any;
        sizeChart: any;
        length: number;
        width: number;
        height: number;
        crossSellProducts: {
            id: string;
        }[];
        crossSells: {
            relatedProductId: string;
        }[];
        options: ({
            values: {
                id: string;
                optionId: string;
                value: string;
                image: string | null;
                position: number;
            }[];
        } & {
            id: string;
            productId: string;
            name: string;
            position: number;
        })[];
        variants: {
            id: string;
            productId: string;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            discountValue: Prisma.Decimal | null;
            stock: number;
            sku: string | null;
            image: string | null;
            tierIndex: string;
        }[];
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    searchMyProducts(userId: string, keyword: string, limit?: number): Promise<{
        id: string;
        name: string;
        price: Prisma.Decimal;
        stock: number;
        images: Prisma.JsonValue;
    }[]>;
    updateDiscount(sellerId: string, productId: string, dto: UpdateProductDiscountDto): Promise<{
        shop: {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            avatar: string | null;
            coverImage: string | null;
            pickupAddress: string | null;
            provinceId: number | null;
            districtId: number | null;
            wardCode: string | null;
            lat: number | null;
            lng: number | null;
            categoryId: string | null;
            status: import("@prisma/client").$Enums.ShopStatus;
            banReason: string | null;
            reviewCount: number;
            decoration: Prisma.JsonValue | null;
            pendingDetails: Prisma.JsonValue | null;
            rating: number;
            totalSales: number;
            ownerId: string;
            address: string | null;
            licenseImage: string | null;
            taxCode: string | null;
            businessLicenseFront: string | null;
            businessLicenseBack: string | null;
            salesLicense: string | null;
            trademarkCert: string | null;
            distributorCert: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        variants: {
            id: string;
            productId: string;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            discountValue: Prisma.Decimal | null;
            stock: number;
            sku: string | null;
            image: string | null;
            tierIndex: string;
        }[];
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    deleteBySeller(userId: string, productId: string): Promise<{
        count: number;
        message?: undefined;
    } | {
        count: number;
        message: string;
    }>;
    findAllBySeller(userId: string, status?: string, opts?: {
        page?: number;
        limit?: number;
        search?: string;
        sortBy?: string;
        sortOrder?: 'asc' | 'desc';
    }): Promise<{
        data: ({
            _count: {
                variants: number;
            };
        } & {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            shortDesc: Prisma.JsonValue | null;
            price: Prisma.Decimal;
            originalPrice: Prisma.Decimal | null;
            stock: number;
            reviewCount: number;
            systemTags: Prisma.JsonValue;
            images: Prisma.JsonValue;
            status: import("@prisma/client").$Enums.ProductStatus;
            rejectReason: string | null;
            attributes: Prisma.JsonValue | null;
            tags: string | null;
            brandId: number | null;
            shopCategoryId: string | null;
            salesCount: number;
            rating: number;
            shopId: string | null;
            weight: number;
            sellerId: string | null;
            categoryId: string | null;
            discountType: import("@prisma/client").$Enums.DiscountType | null;
            discountValue: Prisma.Decimal | null;
            discountStartDate: Date | null;
            discountEndDate: Date | null;
            isDiscountActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        })[];
        meta: {
            total: number;
            page: number;
            limit: number;
            counts: Record<string, number>;
        };
    }>;
    findAllForAdmin(): Promise<({
        shop: {
            id: string;
            name: string;
            slug: string;
            description: string | null;
            avatar: string | null;
            coverImage: string | null;
            pickupAddress: string | null;
            provinceId: number | null;
            districtId: number | null;
            wardCode: string | null;
            lat: number | null;
            lng: number | null;
            categoryId: string | null;
            status: import("@prisma/client").$Enums.ShopStatus;
            banReason: string | null;
            reviewCount: number;
            decoration: Prisma.JsonValue | null;
            pendingDetails: Prisma.JsonValue | null;
            rating: number;
            totalSales: number;
            ownerId: string;
            address: string | null;
            licenseImage: string | null;
            taxCode: string | null;
            businessLicenseFront: string | null;
            businessLicenseBack: string | null;
            salesLicense: string | null;
            trademarkCert: string | null;
            distributorCert: string | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    } & {
        id: string;
        name: string;
        slug: string;
        description: string | null;
        shortDesc: Prisma.JsonValue | null;
        price: Prisma.Decimal;
        originalPrice: Prisma.Decimal | null;
        stock: number;
        reviewCount: number;
        systemTags: Prisma.JsonValue;
        images: Prisma.JsonValue;
        status: import("@prisma/client").$Enums.ProductStatus;
        rejectReason: string | null;
        attributes: Prisma.JsonValue | null;
        tags: string | null;
        brandId: number | null;
        shopCategoryId: string | null;
        salesCount: number;
        rating: number;
        shopId: string | null;
        weight: number;
        sellerId: string | null;
        categoryId: string | null;
        discountType: import("@prisma/client").$Enums.DiscountType | null;
        discountValue: Prisma.Decimal | null;
        discountStartDate: Date | null;
        discountEndDate: Date | null;
        isDiscountActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    private generateSlug;
}
